name: Go-sample

on: [push]

env:
  AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
  OWNER: ivivanov
  DOCKER_REGISTRY: docker.pkg.github.com

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
       
      - name: Go lint
        run: test -z "$(gofmt -s -l . 2>&1 | grep -v vendor | tee /dev/stderr)"          

      - name: Go build
        run: |
          cd go-sample/cmd/demo/
          go build -v .

  docker:
    needs: go
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
     
      - name: Docker login, build & push
        run: |
          docker login -u $OWNER -p $AUTH_TOKEN $DOCKER_REGISTRY
          docker build --tag $DOCKER_REGISTRY/$OWNER/oidc-samples/go-sample:latest go-sample/
          docker push $DOCKER_REGISTRY/$OWNER/oidc-samples/go-sample:latest

  tests:
      needs: docker
      runs-on: ubuntu-latest
      steps:
        - name: Docker pull, run & test
          run: |
            docker login -u $OWNER -p $AUTH_TOKEN $DOCKER_REGISTRY
            docker pull $DOCKER_REGISTRY/$OWNER/oidc-samples/go-sample:latest
            CONTAINER_ID=$(docker run -d -p 8000:8000 --rm $DOCKER_REGISTRY/$OWNER/oidc-samples/go-sample:latest)
            sleep 5
            curl localhost:8000/
            docker container stop $CONTAINER_ID
