name: integration-tests

on:
  push:
    paths:
      - "integration-tests/**"
      - ".github/workflows/integration-tests.yml"

env:
  DOCKER_REGISTRY: docker.pkg.github.com
  USER: ${{ secrets.USER }}
  AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
  INT_TESTS_IMAGE: docker.pkg.github.com/miracl/oidc-samples/integration-tests

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Go lint
        run: test -z "$(gofmt -s -l . 2>&1 | grep -v vendor | tee /dev/stderr)"

  docker:
    needs: go
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Docker login, build & push
        run: |
          docker login -u $USER -p $AUTH_TOKEN $DOCKER_REGISTRY
          docker build --tag $INT_TESTS_IMAGE:latest integration-tests/
          docker push $INT_TESTS_IMAGE:latest
          docker tag $INT_TESTS_IMAGE:latest $INT_TESTS_IMAGE:$GITHUB_SHA
          docker push $INT_TESTS_IMAGE:$GITHUB_SHA
