name: integration-tests

on:
  push:
    paths:
      - "integration-tests/**"
      - ".github/workflows/integration-tests.yml"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: miracl/oidc-samples/integration-tests
  DOCKER_BUILD_CONTEXT: integration-tests

jobs:
  lint-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.*
      - name: Go lint
        run: test -z "$(gofmt -s -l . 2>&1 | grep -v vendor | tee /dev/stderr)"

  build-docker:
    needs: lint-go
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=${{ github.ref == 'refs/heads/master' }}
          tags: |
            type=raw,value=${{ github.sha }}
      - uses: docker/build-push-action@v2
        with:
          context: ${{ env.DOCKER_BUILD_CONTEXT }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
